apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: microservices
  labels:
    app: service-registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: service-registry:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8761"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8761
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: microservices
  labels:
    app: service-registry
spec:
  selector:
    app: service-registry
  ports:
  - port: 80
    targetPort: 8761
    protocol: TCP
    name: http
  type: ClusterIP