name: CI - Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd src/user-service && npm ci
        cd ../email-service && npm ci
        cd ../service-registry && npm ci
        cd ../api-gateway && npm ci

    - name: Run tests
      run: |
        echo "Running tests..."
        # Add your test commands here
        # cd src/user-service && npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./src/user-service/
        docker build -t ${{ secrets.DOCKER_USERNAME }}/email-service:latest ./src/email-service/
        docker build -t ${{ secrets.DOCKER_USERNAME }}/service-registry:latest ./src/service-registry/
        docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ./src/api-gateway/
        
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/email-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/service-registry:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest